// Code generated by goctl. DO NOT EDIT!
// Source: order_detail.proto

package server

import (
	"context"

	"github.com/reation/micro_service_order_service/order_detail/internal/logic"
	"github.com/reation/micro_service_order_service/order_detail/internal/svc"
	"github.com/reation/micro_service_order_service/protoc"
)

type OrderDetailServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedOrderDetailServer
}

func NewOrderDetailServer(svcCtx *svc.ServiceContext) *OrderDetailServer {
	return &OrderDetailServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderDetailServer) GetOrderDetail(ctx context.Context, in *protoc.OrderDetailRequest) (*protoc.OrderDetailResponse, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}
