// Code generated by goctl. DO NOT EDIT!
// Source: order_detail.proto

package orderdetail

import (
	"context"

	"github.com/reation/micro_service_order_service/protoc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderDetailOrderGoodsData = protoc.OrderDetailOrderGoodsData
	OrderDetailOrderInfo      = protoc.OrderDetailOrderInfo
	OrderDetailRequest        = protoc.OrderDetailRequest
	OrderDetailResponse       = protoc.OrderDetailResponse

	OrderDetail interface {
		GetOrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error)
	}

	defaultOrderDetail struct {
		cli zrpc.Client
	}
)

func NewOrderDetail(cli zrpc.Client) OrderDetail {
	return &defaultOrderDetail{
		cli: cli,
	}
}

func (m *defaultOrderDetail) GetOrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderDetailResponse, error) {
	client := protoc.NewOrderDetailClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}
