// Code generated by goctl. DO NOT EDIT!
// Source: order_list.proto

package orderlist

import (
	"context"

	"github.com/reation/micro_service_order_service/protoc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderListGoodsInfo = protoc.OrderListGoodsInfo
	OrderListOrderInfo = protoc.OrderListOrderInfo
	OrderListRequest   = protoc.OrderListRequest
	OrderListResponse  = protoc.OrderListResponse

	OrderList interface {
		GetOrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
	}

	defaultOrderList struct {
		cli zrpc.Client
	}
)

func NewOrderList(cli zrpc.Client) OrderList {
	return &defaultOrderList{
		cli: cli,
	}
}

func (m *defaultOrderList) GetOrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	client := protoc.NewOrderListClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}
