// Code generated by goctl. DO NOT EDIT!
// Source: order_list.proto

package server

import (
	"context"

	"github.com/reation/micro_service_order_service/order_list/internal/logic"
	"github.com/reation/micro_service_order_service/order_list/internal/svc"
	"github.com/reation/micro_service_order_service/protoc"
)

type OrderListServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedOrderListServer
}

func NewOrderListServer(svcCtx *svc.ServiceContext) *OrderListServer {
	return &OrderListServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderListServer) GetOrderList(ctx context.Context, in *protoc.OrderListRequest) (*protoc.OrderListResponse, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}
